url: https://beta.carpentries.org
permalink: /:title/

## Plugins ---------------------------------------------------------------------
plugins:
  - jekyll-assets
  - jekyll-get-json
  - jekyll-last-modified-at


## Variables -------------------------------------------------------------------

### Websites ###

dc_website: https://datacarpentry.org
sc_website: https://software-carpentry.org
lc_website: https://librarycarpentry.org

## Data feeds sources ----------------------------------------------------------

jekyll_get_json:
  - data: all_badged_people
    json: 'https://feeds.carpentries.org/all_badged_people.json'
  - data: all_past_workshops
    json: 'https://feeds.carpentries.org/all_past_workshops.json'
  - data: all_upcoming_workshops
    json: 'https://feeds.carpentries.org/all_upcoming_workshops.json'
  - data: badges_stats
    json: 'https://feeds.carpentries.org/badges_stats.json'
  - data: community_lessons
    json: 'https://feeds.carpentries.org/community_lessons.json'
  - data: help_wanted_issues
    json: 'https://feeds.carpentries.org/help_wanted_issues.json'
  - data: newsletter
    json: 'https://feeds.carpentries.org/newsletter.json'
  - data: members
    json: 'https://feeds.carpentries.org/all_public_memberships.json'
  - data: amy_curricula
    json: 'https://feeds.carpentries.org/amy_curricula.json'


## Assets plugin configuration -------------------------------------------------
assets:
  #compress:
    #css:  scss
    #js:   uglifier
  #external:
  #  uglifier:
  #    harmony: true
  features:
    liquid: true
    integrity: false
  digest: false
  source_maps: true
  sources:
    - _assets/stylesheets
    - _assets/javascripts
    - _assets/images
    - _assets/images/lesson-program-logos
    - _assets/images/flags
    - _assets/downloads
    - _assets/fonts
  plugins:
    img:
      optim:
        default:
          verbose: true
          svgo: false
        optimized:
          verbose: true
          allow_lossy: true
          pack: true
          svgo: true
          pngout: false
          pngcrush: false
          pngquant: false
          advpng: false
          jpegrecompress:
            allow_lossy: true
            quality: 2
          jpegoptim:
            allow_lossy: false
            strip: all
          optipng:
            level: 6

## Files to exclude ------------------------------------------------------------
exclude:
  - README.md
  - vendor
